"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from urllib.parse import urlparse

import dj_database_url
from dotenv import load_dotenv

load_dotenv()


def _host_from_url(url: str) -> str | None:
    if not url or not str(url).strip():
        return None
    h = urlparse(str(url).strip()).hostname
    return h or None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-r_nmpovf4s4dh89130ka(&q(r_!7hpesl)19zbk$&(m1vgw9do')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

# Comma-separated; on Render, also trust RENDER_EXTERNAL_URL so DisallowedHost does not
# require pasting the API hostname (see fromService / dashboard env in render.yaml).
_default_allowed = "localhost,127.0.0.1" if os.getenv("DEBUG", "True").lower() == "true" else ""
ALLOWED_HOSTS_STR = os.getenv("ALLOWED_HOSTS", _default_allowed)
ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_STR.split(",") if host.strip()]
for _url in (os.environ.get("RENDER_EXTERNAL_URL"),):
    h = _host_from_url(_url) if _url else None
    if h and h not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(h)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'whitenoise.runserver_nostatic',  # For serving static files in production
    'chat',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add whitenoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# If DATABASE_URL is set (postgres:// or postgresql:// from Heroku, Render, Railway, etc.),
# dj-database-url configures PostgreSQL. Otherwise use local SQLite.
_sqlite_url = f"sqlite:///{(BASE_DIR / 'db.sqlite3').resolve().as_posix()}"
DATABASES = {
    "default": dj_database_url.config(
        default=_sqlite_url,
        conn_max_age=600,
        ssl_require=os.getenv("DATABASE_SSL_REQUIRE", "false").lower() == "true",
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS: explicit origins; optional regex so *.onrender.com static sites work without
# pre-copying the preview URL. Disable with CORS_TRUST_ONRENDER=false.
CORS_ALLOWED_ORIGINS_STR = os.getenv("CORS_ALLOWED_ORIGINS", "http://localhost:5173")
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ALLOWED_ORIGINS_STR.split(",") if origin.strip()]

# Fallback when CORS_* env is unset: allow any Render HTTPS app origin.
CORS_ALLOWED_ORIGIN_REGEXES = []
if (
    not DEBUG
    and os.getenv("CORS_TRUST_ONRENDER", "true").lower() == "true"
    and bool(os.environ.get("RENDER", "").strip())
):
    CORS_ALLOWED_ORIGIN_REGEXES.append(r"^https://[a-z0-9\-.]+\.onrender\.com$")

CSRF_TRUSTED_ORIGINS_STR = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:5173,http://127.0.0.1:5173",
)
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in CSRF_TRUSTED_ORIGINS_STR.split(",") if origin.strip()
]
# Single origin helper (e.g. set from a Render blueprint to the static site URL)
_fo = os.environ.get("FRONTEND_ORIGIN", "").strip()
if _fo and _fo not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(_fo)
# If CORS lists the production frontend explicitly, also trust it for CSRF.
if not DEBUG and bool(os.environ.get("RENDER", "").strip()):
    for o in CORS_ALLOWED_ORIGINS:
        if o.startswith("https://") and o not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(o)

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'

# -----------------------------------------------------------------------------
# Study gating (sequential sessions, dual arms, 20m wall lock)
# -----------------------------------------------------------------------------
# Comma-separated enrollment codes per arm (defaults allow local dev without .env).
STUDY_CODES_PERSONALIZED = os.getenv(
    "STUDY_CODES_PERSONALIZED",
    "DEV-PERSONALIZED",
)
STUDY_CODES_GENERIC = os.getenv(
    "STUDY_CODES_GENERIC",
    "DEV-GENERIC",
)
# Calendar: first day of week 1 in study timezone (YYYY-MM-DD).
STUDY_START_DATE = os.getenv("STUDY_START_DATE", "2020-01-01")
# IANA timezone for week boundaries and session clock.
STUDY_TIMEZONE = os.getenv("STUDY_TIMEZONE", "UTC")
STUDY_TOTAL_WEEKS = int(os.getenv("STUDY_TOTAL_WEEKS", "8"))
STUDY_INACTIVITY_SECONDS = int(os.getenv("STUDY_INACTIVITY_SECONDS", "600"))
STUDY_HEARTBEAT_MAX_DELTA_SECONDS = int(
    os.getenv("STUDY_HEARTBEAT_MAX_DELTA_SECONDS", "120")
)
STUDY_MEMORY_MAX_CHARS = int(os.getenv("STUDY_MEMORY_MAX_CHARS", "6000"))
STUDY_PROFILE_PERSONALIZED_MAX_SESSION_MINUTES = int(
    os.getenv("STUDY_PROFILE_PERSONALIZED_MAX_SESSION_MINUTES", "20")
)
STUDY_PROFILE_GENERIC_MAX_SESSION_MINUTES = int(
    os.getenv("STUDY_PROFILE_GENERIC_MAX_SESSION_MINUTES", "20")
)
STUDY_PROFILE_PERSONALIZED_DEFAULT_CHARACTER = os.getenv(
    "STUDY_PROFILE_PERSONALIZED_DEFAULT_CHARACTER",
    "default",
)
STUDY_PROFILE_GENERIC_DEFAULT_CHARACTER = os.getenv(
    "STUDY_PROFILE_GENERIC_DEFAULT_CHARACTER",
    "default",
)

# Return login (login code + PIN)
STUDY_PIN_MIN_LENGTH = int(os.getenv("STUDY_PIN_MIN_LENGTH", "4"))
STUDY_PIN_MAX_LENGTH = int(os.getenv("STUDY_PIN_MAX_LENGTH", "6"))
STUDY_LOGIN_CODE_LENGTH = int(os.getenv("STUDY_LOGIN_CODE_LENGTH", "10"))
STUDY_ROTATE_TOKEN_ON_LOGIN = (
    os.getenv("STUDY_ROTATE_TOKEN_ON_LOGIN", "true").lower() == "true"
)

# Production data protection (hosting + ops; Django cannot encrypt disks by itself):
# - Use HTTPS (see SECURE_SSL_REDIRECT when DEBUG=False).
# - Use a managed database with encryption at rest and restricted network access.
# - Restrict Django admin; rotate SECRET_KEY; define retention in participant consent.