# Generated by Django 5.2.3 on 2025-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='messages',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
