# Generated by Django 5.2.3 on 2025-12-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversation_messages_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='audit',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
