# Generated by Django 5.2.3 on 2026-05-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_participant_login_code_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='caiq_panas_submitted_at',
            field=models.DateTimeField(blank=True, help_text='CAIQ-PANAS batch saved before session completion.', null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='reading_questionnaire_submitted_at',
            field=models.DateTimeField(blank=True, help_text='Likert + comprehension (slot 3) saved; CAIQ-PANAS may still be pending.', null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='survey_scores',
            field=models.JSONField(blank=True, help_text='Aggregates from CAIQ-PANAS scoring after successful survey submit.', null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='condition',
            field=models.CharField(choices=[('personalized', 'Personalized'), ('generic', 'Generic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='locked', max_length=20),
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('participant_code', models.CharField(db_index=True, help_text='Login code (or fallback id) at submission time.', max_length=32)),
                ('condition', models.CharField(max_length=20)),
                ('session_number', models.PositiveSmallIntegerField()),
                ('survey_version', models.CharField(choices=[('full', 'Full'), ('mini', 'Mini')], max_length=10)),
                ('item_id', models.CharField(db_index=True, max_length=32)),
                ('item_text', models.TextField()),
                ('value', models.PositiveSmallIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('completion_status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial')], default='complete', max_length=16)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='chat.participant')),
                ('study_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_responses', to='chat.studysession')),
            ],
            options={
                'ordering': ['study_session_id', 'item_id'],
            },
        ),
    ]
